version: "3.9"

services:
  app:
    build: .
    restart: always
    depends_on:
      - mongo
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_db:/data/db

volumes:
  logs:
  mongo_db: